name: Monorepo Package CI

on:
  pull_request:
    branches:
      - dev

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      hooks: ${{ steps.filter.outputs.hooks }}
      components: ${{ steps.filter.outputs.components }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect changed packages
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            hooks:
              - 'packages/hooks/**'
            components:
              - 'packages/components/**'

  hooks-test:
    needs: changes
    if: needs.changes.outputs.hooks == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-setup-node

      - name: Run hooks tests
        working-directory: packages/hooks
        run: npm test

  components-test:
    needs: changes
    if: needs.changes.outputs.components == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/npm-setup-node

      - name: Run components tests
        working-directory: packages/components
        run: npm test
